# Generated by Django 3.2.8 on 2021-11-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
