# Generated by Django 3.2.8 on 2021-11-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='banner',
            field=models.ImageField(upload_to='post banners', verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(upload_to='posts', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='posts.PostTagModel', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=512, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='posttagmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='posttagmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
