# Generated by Django 4.0 on 2021-12-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211125_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='title_en',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title_ru',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title_uz',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
    ]
