# Generated by Django 4.0 on 2022-01-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postmodel_title_en_postmodel_title_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='short_description',
            field=models.TextField(default=0),
        ),
    ]
