# Generated by Django 4.0 on 2022-01-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_postmodel_title_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='short_description_en',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='short_description_ru',
            field=models.TextField(default=0, null=True),
        ),
    ]
