# Generated by Django 4.0 on 2021-12-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_tripmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='placemodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
    ]
