# Generated by Django 4.0 on 2021-12-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homemodel_price_alter_placemodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='place',
            field=models.TextField(max_length=50),
        ),
    ]
