# Generated by Django 4.0 on 2021-12-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_homemodel_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='place',
            field=models.IntegerField(),
        ),
    ]
