# Generated by Django 4.0 on 2021-12-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_homemodel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homemodel',
            old_name='price',
            new_name='remains',
        ),
    ]
