# Generated by Django 4.0 on 2021-12-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rename_price_homemodel_remains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='remains',
            field=models.TextField(max_length=50),
        ),
    ]
