# Generated by Django 4.0 on 2021-12-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='place_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='place_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='place_uz',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='remains_en',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='remains_ru',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='remains_uz',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='placemodel',
            name='price_en',
            field=models.IntegerField(default=0, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='placemodel',
            name='price_ru',
            field=models.IntegerField(default=0, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='placemodel',
            name='price_uz',
            field=models.IntegerField(default=0, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='placemodel',
            name='title_en',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='placemodel',
            name='title_ru',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='placemodel',
            name='title_uz',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
