# Generated by Django 3.2.8 on 2021-11-09 04:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourmodel',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, verbose_name='long_description'),
        ),
    ]
