# Generated by Django 3.2.8 on 2021-11-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tourmodel_long_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tour tag',
                'verbose_name_plural': 'tour tag',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
