# Generated by Django 3.2.8 on 2021-11-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20211115_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tours', to='tours.TourTagModel', verbose_name='tags'),
        ),
    ]
