# Generated by Django 4.0 on 2021-12-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_ordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
