# Generated by Django 4.0 on 2021-12-20 12:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_delete_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmodel',
            name='long_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='long_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='long_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='price_en',
            field=models.IntegerField(default=0, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='price_ru',
            field=models.IntegerField(default=0, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='price_uz',
            field=models.IntegerField(default=0, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='title_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
    ]
