# Generated by Django 4.0 on 2022-01-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tourmodel_long_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourmodel',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='tourmodel',
            name='long_description_en',
        ),
        migrations.RemoveField(
            model_name='tourmodel',
            name='long_description_ru',
        ),
        migrations.RemoveField(
            model_name='tourmodel',
            name='long_description_uz',
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='short_description',
            field=models.TextField(default=0),
        ),
    ]
