# Generated by Django 4.0 on 2022-01-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_remove_tourmodel_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmodel',
            name='short_description_en',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='short_description_ru',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='short_description_uz',
            field=models.TextField(default=0, null=True),
        ),
    ]
