# Generated by Django 4.0 on 2022-01-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_rename_name_category_title_tourhotelmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourmodel',
            name='price_uz',
        ),
        migrations.RemoveField(
            model_name='tourmodel',
            name='short_description_uz',
        ),
        migrations.RemoveField(
            model_name='tourmodel',
            name='title_uz',
        ),
    ]
