# Generated by Django 4.0 on 2021-12-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
