# Generated by Django 4.0 on 2021-12-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_email_ordermodel_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='messages',
            field=models.TextField(null=True),
        ),
    ]
