# Generated by Django 4.0 on 2021-12-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_ordermodel_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
