# Generated by Django 4.0 on 2022-01-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
